---
- name: start VM 
  hosts: localhost
  vars_files: vars.yml
  become: false
  gather_facts: false
  collections:
    - community.vmware
  tasks:
  - name: deploy VM
    vmware_guest: 
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: False
      datacenter: Datacenter
      datastore: datastore_6TB
      folder: centos
      template: t_centos8
      name: centos8-boot
      networks:
        - name: VMs11
          ip: "10.100.11.103"
          netmask: "255.255.255.0"
          gateway: "10.100.11.254"
      customization:
        hostname: "centos-boot"
        dns_servers: [10.100.11.200]
      state: powered-off
    register: deploy
  - name: Change VM boot parameters
    vmware_guest_boot_manager:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: False
      name: centos8-boot
      boot_delay: 10000
      boot_firmware: efi
      secure_boot_enabled: false
    delegate_to: localhost
    register: vm_boot
    tags:
      - boot_change

